# fastapi-backend/nixpacks.toml
providers = ['...', 'python']  # force Python provider
[phases.setup]
aptPkgs = ['...', 'ffmpeg']    # install ffmpeg on Ubuntu base
[start]
cmd = "uvicorn app.app:app --host 0.0.0.0 --port 8000"
